//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int Uid { get; set; }
        public string UrunAdi { get; set; }
        public string barkod { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> Birim { get; set; }
        public Nullable<System.DateTime> rafOmru { get; set; }
        public string mensei { get; set; }
    }
}
