//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int uid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> islogin { get; set; }
        public string SessionId { get; set; }
        public string ipAddress { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
        public Nullable<int> loginCount { get; set; }
        public string webBrowser { get; set; }
    }
}
